"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FollowStruct(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FOLLOWER_ID_FIELD_NUMBER: builtins.int
    FOLLOWING_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    follower_id: builtins.str
    following_id: builtins.str
    created_at: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        follower_id: builtins.str = ...,
        following_id: builtins.str = ...,
        created_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "follower_id", b"follower_id", "following_id", b"following_id", "id", b"id"]) -> None: ...

global___FollowStruct = FollowStruct

@typing.final
class UserStruct(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    NUMTWEETS_FIELD_NUMBER: builtins.int
    NUMFOLLOWERS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    email: builtins.str
    username: builtins.str
    numTweets: builtins.int
    numFollowers: builtins.int
    created_at: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        email: builtins.str = ...,
        username: builtins.str = ...,
        numTweets: builtins.int = ...,
        numFollowers: builtins.int = ...,
        created_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "email", b"email", "id", b"id", "numFollowers", b"numFollowers", "numTweets", b"numTweets", "username", b"username"]) -> None: ...

global___UserStruct = UserStruct

@typing.final
class GetUserReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___GetUserReq = GetUserReq

@typing.final
class GetUserRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALID_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    valid: builtins.bool
    @property
    def user(self) -> global___UserStruct: ...
    def __init__(
        self,
        *,
        valid: builtins.bool = ...,
        user: global___UserStruct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user", b"user", "valid", b"valid"]) -> None: ...

global___GetUserRes = GetUserRes

@typing.final
class IncrementTweetsReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___IncrementTweetsReq = IncrementTweetsReq

@typing.final
class IncrementTweetsRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

global___IncrementTweetsRes = IncrementTweetsRes

@typing.final
class GetFollowersReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___GetFollowersReq = GetFollowersReq

@typing.final
class GetFollowersRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLLOWERS_FIELD_NUMBER: builtins.int
    @property
    def followers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FollowStruct]: ...
    def __init__(
        self,
        *,
        followers: collections.abc.Iterable[global___FollowStruct] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["followers", b"followers"]) -> None: ...

global___GetFollowersRes = GetFollowersRes

@typing.final
class GetFollowingReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___GetFollowingReq = GetFollowingReq

@typing.final
class GetFollowingRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLLWING_FIELD_NUMBER: builtins.int
    @property
    def follwing(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FollowStruct]: ...
    def __init__(
        self,
        *,
        follwing: collections.abc.Iterable[global___FollowStruct] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["follwing", b"follwing"]) -> None: ...

global___GetFollowingRes = GetFollowingRes
