# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tweet_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tweet_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tweet_service.proto\x12\rtweet_service\"\x8b\x01\n\x0bTweetStruct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\tnum_likes\x18\x04 \x01(\x05\x12\x12\n\nnum_replys\x18\x05 \x01(\x05\x12\x13\n\x0bnum_reposts\x18\x06 \x01(\x05\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\"!\n\x0cGetTweetsReq\x12\x11\n\ttweet_ids\x18\x01 \x03(\t\":\n\x0cGetTweetsRes\x12*\n\x06tweets\x18\x01 \x03(\x0b\x32\x1a.tweet_service.TweetStruct2N\n\x05Tweet\x12\x45\n\tGetTweets\x12\x1b.tweet_service.GetTweetsReq\x1a\x1b.tweet_service.GetTweetsResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tweet_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TWEETSTRUCT']._serialized_start=39
  _globals['_TWEETSTRUCT']._serialized_end=178
  _globals['_GETTWEETSREQ']._serialized_start=180
  _globals['_GETTWEETSREQ']._serialized_end=213
  _globals['_GETTWEETSRES']._serialized_start=215
  _globals['_GETTWEETSRES']._serialized_end=273
  _globals['_TWEET']._serialized_start=275
  _globals['_TWEET']._serialized_end=353
# @@protoc_insertion_point(module_scope)
