# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"Y\n\x0c\x46ollowStruct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x66ollower_id\x18\x02 \x01(\t\x12\x14\n\x0c\x66ollowing_id\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"v\n\nUserStruct\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x11\n\tnumTweets\x18\x04 \x01(\x05\x12\x14\n\x0cnumFollowers\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"\x1d\n\nGetUserReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"C\n\nGetUserRes\x12\r\n\x05valid\x18\x01 \x01(\x08\x12&\n\x04user\x18\x02 \x01(\x0b\x32\x18.user_service.UserStruct\"%\n\x12IncrementTweetsReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"%\n\x12IncrementTweetsRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x0fGetFollowersReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"@\n\x0fGetFollowersRes\x12-\n\tfollowers\x18\x01 \x03(\x0b\x32\x1a.user_service.FollowStruct\"\"\n\x0fGetFollowingReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"?\n\x0fGetFollowingRes\x12,\n\x08\x66ollwing\x18\x01 \x03(\x0b\x32\x1a.user_service.FollowStruct2\xb9\x02\n\x04User\x12=\n\x07GetUser\x12\x18.user_service.GetUserReq\x1a\x18.user_service.GetUserRes\x12V\n\x10IncrementsTweets\x12 .user_service.IncrementTweetsReq\x1a .user_service.IncrementTweetsRes\x12L\n\x0cGetFollowers\x12\x1d.user_service.GetFollowersReq\x1a\x1d.user_service.GetFollowersRes\x12L\n\x0cGetFollowing\x12\x1d.user_service.GetFollowingReq\x1a\x1d.user_service.GetFollowingResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLLOWSTRUCT']._serialized_start=36
  _globals['_FOLLOWSTRUCT']._serialized_end=125
  _globals['_USERSTRUCT']._serialized_start=127
  _globals['_USERSTRUCT']._serialized_end=245
  _globals['_GETUSERREQ']._serialized_start=247
  _globals['_GETUSERREQ']._serialized_end=276
  _globals['_GETUSERRES']._serialized_start=278
  _globals['_GETUSERRES']._serialized_end=345
  _globals['_INCREMENTTWEETSREQ']._serialized_start=347
  _globals['_INCREMENTTWEETSREQ']._serialized_end=384
  _globals['_INCREMENTTWEETSRES']._serialized_start=386
  _globals['_INCREMENTTWEETSRES']._serialized_end=423
  _globals['_GETFOLLOWERSREQ']._serialized_start=425
  _globals['_GETFOLLOWERSREQ']._serialized_end=459
  _globals['_GETFOLLOWERSRES']._serialized_start=461
  _globals['_GETFOLLOWERSRES']._serialized_end=525
  _globals['_GETFOLLOWINGREQ']._serialized_start=527
  _globals['_GETFOLLOWINGREQ']._serialized_end=561
  _globals['_GETFOLLOWINGRES']._serialized_start=563
  _globals['_GETFOLLOWINGRES']._serialized_end=626
  _globals['_USER']._serialized_start=629
  _globals['_USER']._serialized_end=942
# @@protoc_insertion_point(module_scope)
