// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowerId    string                 `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   string                 `protobuf:"bytes,3,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowStruct) Reset() {
	*x = FollowStruct{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowStruct) ProtoMessage() {}

func (x *FollowStruct) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowStruct.ProtoReflect.Descriptor instead.
func (*FollowStruct) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *FollowStruct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FollowStruct) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowStruct) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

func (x *FollowStruct) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UserStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	NumTweets     int32                  `protobuf:"varint,4,opt,name=numTweets,proto3" json:"numTweets,omitempty"`
	NumFollowers  int32                  `protobuf:"varint,5,opt,name=numFollowers,proto3" json:"numFollowers,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStruct) Reset() {
	*x = UserStruct{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStruct) ProtoMessage() {}

func (x *UserStruct) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStruct.ProtoReflect.Descriptor instead.
func (*UserStruct) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserStruct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserStruct) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserStruct) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStruct) GetNumTweets() int32 {
	if x != nil {
		return x.NumTweets
	}
	return 0
}

func (x *UserStruct) GetNumFollowers() int32 {
	if x != nil {
		return x.NumFollowers
	}
	return 0
}

func (x *UserStruct) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *UserStruct            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRes) Reset() {
	*x = GetUserRes{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRes) ProtoMessage() {}

func (x *GetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRes.ProtoReflect.Descriptor instead.
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRes) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GetUserRes) GetUser() *UserStruct {
	if x != nil {
		return x.User
	}
	return nil
}

type IncrementTweetsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementTweetsReq) Reset() {
	*x = IncrementTweetsReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementTweetsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementTweetsReq) ProtoMessage() {}

func (x *IncrementTweetsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementTweetsReq.ProtoReflect.Descriptor instead.
func (*IncrementTweetsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementTweetsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IncrementTweetsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementTweetsRes) Reset() {
	*x = IncrementTweetsRes{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementTweetsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementTweetsRes) ProtoMessage() {}

func (x *IncrementTweetsRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementTweetsRes.ProtoReflect.Descriptor instead.
func (*IncrementTweetsRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementTweetsRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFollowersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersReq) Reset() {
	*x = GetFollowersReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersReq) ProtoMessage() {}

func (x *GetFollowersReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersReq.ProtoReflect.Descriptor instead.
func (*GetFollowersReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*FollowStruct        `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRes) Reset() {
	*x = GetFollowersRes{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRes) ProtoMessage() {}

func (x *GetFollowersRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRes.ProtoReflect.Descriptor instead.
func (*GetFollowersRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowersRes) GetFollowers() []*FollowStruct {
	if x != nil {
		return x.Followers
	}
	return nil
}

type GetFollowingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingReq) Reset() {
	*x = GetFollowingReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingReq) ProtoMessage() {}

func (x *GetFollowingReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingReq.ProtoReflect.Descriptor instead.
func (*GetFollowingReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowingReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follwing      []*FollowStruct        `protobuf:"bytes,1,rep,name=follwing,proto3" json:"follwing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRes) Reset() {
	*x = GetFollowingRes{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRes) ProtoMessage() {}

func (x *GetFollowingRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRes.ProtoReflect.Descriptor instead.
func (*GetFollowingRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowingRes) GetFollwing() []*FollowStruct {
	if x != nil {
		return x.Follwing
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\x81\x01\n" +
	"\fFollowStruct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x03 \x01(\tR\vfollowingId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xaf\x01\n" +
	"\n" +
	"UserStruct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1c\n" +
	"\tnumTweets\x18\x04 \x01(\x05R\tnumTweets\x12\"\n" +
	"\fnumFollowers\x18\x05 \x01(\x05R\fnumFollowers\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"%\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\n" +
	"GetUserRes\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.user.UserStructR\x04user\"-\n" +
	"\x12IncrementTweetsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x12IncrementTweetsRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fGetFollowersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x0fGetFollowersRes\x120\n" +
	"\tfollowers\x18\x01 \x03(\v2\x12.user.FollowStructR\tfollowers\"*\n" +
	"\x0fGetFollowingReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x0fGetFollowingRes\x12.\n" +
	"\bfollwing\x18\x01 \x03(\v2\x12.user.FollowStructR\bfollwing2\xf9\x01\n" +
	"\x04User\x12-\n" +
	"\aGetUser\x12\x10.user.GetUserReq\x1a\x10.user.GetUserRes\x12F\n" +
	"\x10IncrementsTweets\x12\x18.user.IncrementTweetsReq\x1a\x18.user.IncrementTweetsRes\x12<\n" +
	"\fGetFollowers\x12\x15.user.GetFollowersReq\x1a\x15.user.GetFollowersRes\x12<\n" +
	"\fGetFollowing\x12\x15.user.GetFollowingReq\x1a\x15.user.GetFollowingResB\x13Z\x11tweet-worker/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_goTypes = []any{
	(*FollowStruct)(nil),       // 0: user.FollowStruct
	(*UserStruct)(nil),         // 1: user.UserStruct
	(*GetUserReq)(nil),         // 2: user.GetUserReq
	(*GetUserRes)(nil),         // 3: user.GetUserRes
	(*IncrementTweetsReq)(nil), // 4: user.IncrementTweetsReq
	(*IncrementTweetsRes)(nil), // 5: user.IncrementTweetsRes
	(*GetFollowersReq)(nil),    // 6: user.GetFollowersReq
	(*GetFollowersRes)(nil),    // 7: user.GetFollowersRes
	(*GetFollowingReq)(nil),    // 8: user.GetFollowingReq
	(*GetFollowingRes)(nil),    // 9: user.GetFollowingRes
}
var file_user_proto_depIdxs = []int32{
	1, // 0: user.GetUserRes.user:type_name -> user.UserStruct
	0, // 1: user.GetFollowersRes.followers:type_name -> user.FollowStruct
	0, // 2: user.GetFollowingRes.follwing:type_name -> user.FollowStruct
	2, // 3: user.User.GetUser:input_type -> user.GetUserReq
	4, // 4: user.User.IncrementsTweets:input_type -> user.IncrementTweetsReq
	6, // 5: user.User.GetFollowers:input_type -> user.GetFollowersReq
	8, // 6: user.User.GetFollowing:input_type -> user.GetFollowingReq
	3, // 7: user.User.GetUser:output_type -> user.GetUserRes
	5, // 8: user.User.IncrementsTweets:output_type -> user.IncrementTweetsRes
	7, // 9: user.User.GetFollowers:output_type -> user.GetFollowersRes
	9, // 10: user.User.GetFollowing:output_type -> user.GetFollowingRes
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
